2025-08-07 00:05:02,224 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:05:02,224 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:05:02,474 [ERROR] __main__ - Shutdown error: 'Config' object has no attribute 'USE_WEBHOOK'
2025-08-07 00:05:05,430 [INFO] __main__ - Starting bot in polling mode
2025-08-07 00:05:05,446 [INFO] __main__ - Database initialized successfully
2025-08-07 00:05:05,725 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:05:05,809 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:05:06,742 [INFO] api.onlypays_api - OnlyPays get_status response: {'success': True, 'data': {'id': 'hvebkz23lu', 'status': 'waiting', 'personal_id': '5', 'received_sum': None}}
2025-08-07 00:05:06,742 [INFO] api.api_manager - Статус заказа hvebkz23lu от OnlyPays: {'success': True, 'data': {'id': 'hvebkz23lu', 'status': 'waiting', 'personal_id': '5', 'received_sum': None}, 'api_name': 'OnlyPays'}
2025-08-07 00:05:07,059 [INFO] aiogram.event - Update id=182330583 is handled. Duration 765 ms by bot id=8153616825
2025-08-07 00:05:08,715 [INFO] handlers.user - Received message: ❌ Отменить заявку, user_id: 7004205562
2025-08-07 00:05:08,715 [INFO] handlers.user - State data: {}
2025-08-07 00:05:08,839 [INFO] aiogram.event - Update id=182330584 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:05:09,764 [INFO] handlers.user - Received message: ✅ Подтвердить заявку, user_id: 7004205562
2025-08-07 00:05:09,765 [INFO] handlers.user - State data: {}
2025-08-07 00:05:09,891 [INFO] aiogram.event - Update id=182330585 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:05:12,372 [INFO] handlers.user - Received message: ✅ Подтвердить заявку, user_id: 7004205562
2025-08-07 00:05:12,372 [INFO] handlers.user - State data: {}
2025-08-07 00:05:12,546 [INFO] aiogram.event - Update id=182330586 is handled. Duration 171 ms by bot id=8153616825
2025-08-07 00:05:54,864 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:05:54,866 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:05:55,118 [ERROR] __main__ - Shutdown error: 'Config' object has no attribute 'USE_WEBHOOK'
2025-08-07 00:07:03,078 [INFO] __main__ - Starting bot in polling mode
2025-08-07 00:07:03,078 [INFO] __main__ - Database initialized successfully
2025-08-07 00:07:03,340 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:07:03,420 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:07:14,845 [INFO] aiogram.event - Update id=182330587 is not handled. Duration 0 ms by bot id=8153616825
2025-08-07 00:07:16,597 [INFO] aiogram.event - Update id=182330588 is not handled. Duration 16 ms by bot id=8153616825
2025-08-07 00:07:20,019 [INFO] aiogram.event - Update id=182330589 is handled. Duration 407 ms by bot id=8153616825
2025-08-07 00:07:21,279 [INFO] aiogram.event - Update id=182330590 is handled. Duration 94 ms by bot id=8153616825
2025-08-07 00:07:27,189 [INFO] aiogram.event - Update id=182330591 is handled. Duration 578 ms by bot id=8153616825
2025-08-07 00:07:29,296 [INFO] aiogram.event - Update id=182330592 is handled. Duration 280 ms by bot id=8153616825
2025-08-07 00:07:30,144 [INFO] aiogram.event - Update id=182330593 is handled. Duration 94 ms by bot id=8153616825
2025-08-07 00:07:31,462 [INFO] aiogram.event - Update id=182330594 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:07:32,713 [INFO] aiogram.event - Update id=182330595 is handled. Duration 188 ms by bot id=8153616825
2025-08-07 00:07:32,718 [INFO] api.api_manager - Вызов create_order для OnlyPays с параметрами: amount=2500, pay_types=sbp, personal_id=6, wallet=None
2025-08-07 00:07:32,718 [INFO] api.api_manager - Попытка создания заказа через OnlyPays (тип платежа: sbp -> sbp)
2025-08-07 00:07:37,101 [INFO] api.onlypays_api - OnlyPays create_order response (sum 2500): {'success': False, 'error': 'No available requisites'}
2025-08-07 00:07:37,102 [WARNING] api.api_manager - OnlyPays не смог создать заказ: No available requisites
2025-08-07 00:07:37,102 [INFO] api.api_manager - Вызов create_order для PSPWare с параметрами: amount=2500, pay_types=['sbp'], personal_id=6, wallet=None
2025-08-07 00:07:37,104 [INFO] api.api_manager - Попытка создания заказа через PSPWare (тип платежа: sbp -> sbp)
2025-08-07 00:07:37,105 [INFO] api.pspware_api - [PSPWareAPI] POST https://api.pspware.space/merchant/v2/orders Headers: {'X-API-KEY': 'd6e4d661-665d-4220-a635-4d072e56735b', 'Content-Type': 'application/json'} Payload: {'sum': 2500, 'currency': 'RUB', 'order_type': 'PAY-IN', 'pay_types': ['sbp'], 'geos': ['RU'], 'merchant_id': '03d6d735-a2b7-4b75-b5fa-43be40331bf8', 'order_id': '6', 'description': 'Exchange order 6'}
2025-08-07 00:07:37,579 [INFO] api.pspware_api - [PSPWareAPI] Response status 404 Body: {"detail":"Не удалось найти подходящие реквизиты ни по одному из способов оплаты."}
2025-08-07 00:07:37,580 [ERROR] api.pspware_api - [PSPWareAPI] Ошибка создания заказа: {'detail': 'Не удалось найти подходящие реквизиты ни по одному из способов оплаты.'}
2025-08-07 00:07:37,582 [WARNING] api.api_manager - PSPWare не смог создать заказ: Не удалось найти подходящие реквизиты ни по одному из способов оплаты.
2025-08-07 00:07:37,582 [INFO] api.api_manager - Вызов create_order для Greengo с параметрами: amount=2500, pay_types=sbp, personal_id=6, wallet=bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz
2025-08-07 00:07:37,583 [INFO] api.api_manager - Попытка создания заказа через Greengo (тип платежа: sbp -> sbp)
2025-08-07 00:07:37,584 [INFO] api.greengo_api - Создание Greengo ордера: {'payment_method': 'sbp', 'wallet': 'bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz', 'from_amount': '2500'}
2025-08-07 00:07:40,034 [ERROR] api.greengo_api - Greengo HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:07:40,036 [WARNING] api.api_manager - Greengo не смог создать заказ: HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:07:40,036 [INFO] api.api_manager - Вызов create_order для NicePay с параметрами: amount=2500, pay_types=sbp_rub, personal_id=6, wallet=None
2025-08-07 00:07:40,037 [INFO] api.api_manager - Попытка создания заказа через NicePay (тип платежа: sbp -> sbp_rub)
2025-08-07 00:07:40,329 [INFO] api.nicepay_api - NicePay response: {'status': 'success', 'data': {'payment_id': '4lT689-3c40ed-d5ec94-1b0ab1-f90QVW', 'amount': 250000, 'currency': 'RUB', 'link': 'https://processinglink.io/pay/4lT689-3c40ed-d5ec94-1b0ab1-f90QVW', 'expired': 1754532446}}
2025-08-07 00:07:40,331 [INFO] api.api_manager - Успешное создание заказа через NicePay: {'id': '6', 'order_id': '6', 'payment_url': 'https://processinglink.io/pay/4lT689-3c40ed-d5ec94-1b0ab1-f90QVW', 'amount': 2500}
2025-08-07 00:07:47,757 [INFO] aiogram.event - Update id=182330596 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:08:18,756 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:08:18,756 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:08:19,008 [ERROR] __main__ - Shutdown error: 'Config' object has no attribute 'USE_WEBHOOK'
2025-08-07 00:08:22,085 [INFO] __main__ - Starting bot in polling mode
2025-08-07 00:08:22,085 [INFO] __main__ - Database initialized successfully
2025-08-07 00:08:22,354 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:08:22,431 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:08:25,051 [INFO] aiogram.event - Update id=182330597 is handled. Duration 327 ms by bot id=8153616825
2025-08-07 00:08:26,565 [INFO] aiogram.event - Update id=182330598 is handled. Duration 140 ms by bot id=8153616825
2025-08-07 00:13:34,123 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:13:34,125 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:13:34,393 [ERROR] __main__ - Shutdown error: 'Config' object has no attribute 'USE_WEBHOOK'
2025-08-07 00:13:38,151 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:13:38,220 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:13:48,295 [INFO] aiogram.event - Update id=182330599 is handled. Duration 327 ms by bot id=8153616825
2025-08-07 00:13:50,318 [INFO] aiogram.event - Update id=182330600 is handled. Duration 469 ms by bot id=8153616825
2025-08-07 00:13:52,591 [INFO] aiogram.event - Update id=182330601 is handled. Duration 141 ms by bot id=8153616825
2025-08-07 00:13:55,244 [INFO] aiogram.event - Update id=182330602 is handled. Duration 250 ms by bot id=8153616825
2025-08-07 00:13:57,644 [INFO] aiogram.event - Update id=182330603 is handled. Duration 219 ms by bot id=8153616825
2025-08-07 00:14:04,034 [INFO] aiogram.event - Update id=182330604 is handled. Duration 94 ms by bot id=8153616825
2025-08-07 00:14:05,171 [INFO] aiogram.event - Update id=182330605 is handled. Duration 438 ms by bot id=8153616825
2025-08-07 00:14:06,258 [INFO] aiogram.event - Update id=182330606 is handled. Duration 296 ms by bot id=8153616825
2025-08-07 00:14:07,053 [INFO] aiogram.event - Update id=182330607 is handled. Duration 109 ms by bot id=8153616825
2025-08-07 00:14:13,204 [INFO] aiogram.event - Update id=182330608 is handled. Duration 140 ms by bot id=8153616825
2025-08-07 00:14:16,070 [INFO] aiogram.event - Update id=182330609 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:14:16,079 [INFO] api.api_manager - Вызов create_order для OnlyPays с параметрами: amount=2500, pay_types=card, personal_id=7, wallet=None
2025-08-07 00:14:16,080 [INFO] api.api_manager - Попытка создания заказа через OnlyPays (тип платежа: card -> card)
2025-08-07 00:14:21,589 [INFO] api.onlypays_api - OnlyPays create_order response (sum 2500): {'success': False, 'error': 'No available requisites'}
2025-08-07 00:14:21,591 [WARNING] api.api_manager - OnlyPays не смог создать заказ: No available requisites
2025-08-07 00:14:21,592 [INFO] api.api_manager - Вызов create_order для PSPWare с параметрами: amount=2500, pay_types=['c2c'], personal_id=7, wallet=None
2025-08-07 00:14:21,593 [INFO] api.api_manager - Попытка создания заказа через PSPWare (тип платежа: card -> c2c)
2025-08-07 00:14:21,593 [INFO] api.pspware_api - [PSPWareAPI] POST https://api.pspware.space/merchant/v2/orders Headers: {'X-API-KEY': 'd6e4d661-665d-4220-a635-4d072e56735b', 'Content-Type': 'application/json'} Payload: {'sum': 2500, 'currency': 'RUB', 'order_type': 'PAY-IN', 'pay_types': ['c2c'], 'geos': ['RU'], 'merchant_id': '03d6d735-a2b7-4b75-b5fa-43be40331bf8', 'order_id': '7', 'description': 'Exchange order 7'}
2025-08-07 00:14:22,115 [INFO] api.pspware_api - [PSPWareAPI] Response status 404 Body: {"detail":"Не удалось найти подходящие реквизиты ни по одному из способов оплаты."}
2025-08-07 00:14:22,116 [ERROR] api.pspware_api - [PSPWareAPI] Ошибка создания заказа: {'detail': 'Не удалось найти подходящие реквизиты ни по одному из способов оплаты.'}
2025-08-07 00:14:22,118 [WARNING] api.api_manager - PSPWare не смог создать заказ: Не удалось найти подходящие реквизиты ни по одному из способов оплаты.
2025-08-07 00:14:22,119 [INFO] api.api_manager - Вызов create_order для Greengo с параметрами: amount=2500, pay_types=card, personal_id=7, wallet=bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz
2025-08-07 00:14:22,120 [INFO] api.api_manager - Попытка создания заказа через Greengo (тип платежа: card -> card)
2025-08-07 00:14:22,121 [INFO] api.greengo_api - Создание Greengo ордера: {'payment_method': 'card', 'wallet': 'bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz', 'from_amount': '2500'}
2025-08-07 00:14:24,930 [ERROR] api.greengo_api - Greengo HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:14:24,932 [WARNING] api.api_manager - Greengo не смог создать заказ: HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:14:24,933 [INFO] api.api_manager - Вызов create_order для NicePay с параметрами: amount=2500, pay_types=sberbank_rub, personal_id=7, wallet=None
2025-08-07 00:14:24,933 [INFO] api.api_manager - Попытка создания заказа через NicePay (тип платежа: card -> sberbank_rub)
2025-08-07 00:14:25,213 [INFO] api.nicepay_api - NicePay response: {'status': 'success', 'data': {'payment_id': 'bQj689-3c5a3d-d5ec94-1b0ab1-fa2V2l', 'amount': 250000, 'currency': 'RUB', 'link': 'https://processinglink.io/pay/bQj689-3c5a3d-d5ec94-1b0ab1-fa2V2l', 'expired': 1754532851}}
2025-08-07 00:14:25,215 [INFO] api.api_manager - Успешное создание заказа через NicePay: {'id': '7', 'order_id': '7', 'payment_url': 'https://processinglink.io/pay/bQj689-3c5a3d-d5ec94-1b0ab1-fa2V2l', 'amount': 2500}
2025-08-07 00:15:51,609 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:15:51,609 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:15:51,863 [ERROR] asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py:64> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 66, in main
    await run_polling()
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 55, in run_polling
    await dp.start_polling(bot, skip_updates=True)
  File "C:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 543, in start_polling
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 75, in main
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2025-08-07 00:15:55,273 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:15:55,341 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:15:58,648 [INFO] aiogram.event - Update id=182330610 is handled. Duration 297 ms by bot id=8153616825
2025-08-07 00:15:59,560 [INFO] aiogram.event - Update id=182330611 is handled. Duration 109 ms by bot id=8153616825
2025-08-07 00:16:01,101 [INFO] aiogram.event - Update id=182330612 is handled. Duration 375 ms by bot id=8153616825
2025-08-07 00:16:02,719 [INFO] aiogram.event - Update id=182330613 is handled. Duration 282 ms by bot id=8153616825
2025-08-07 00:16:03,868 [INFO] aiogram.event - Update id=182330614 is handled. Duration 109 ms by bot id=8153616825
2025-08-07 00:16:08,471 [INFO] aiogram.event - Update id=182330615 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:16:09,658 [INFO] aiogram.event - Update id=182330616 is handled. Duration 94 ms by bot id=8153616825
2025-08-07 00:16:09,665 [INFO] api.api_manager - Вызов create_order для OnlyPays с параметрами: amount=2500, pay_types=card, personal_id=8, wallet=None
2025-08-07 00:16:09,665 [INFO] api.api_manager - Попытка создания заказа через OnlyPays (тип платежа: card -> card)
2025-08-07 00:16:13,819 [INFO] api.onlypays_api - OnlyPays create_order response (sum 2500): {'success': False, 'error': 'No available requisites'}
2025-08-07 00:16:13,820 [WARNING] api.api_manager - OnlyPays не смог создать заказ: No available requisites
2025-08-07 00:16:13,821 [INFO] api.api_manager - Вызов create_order для PSPWare с параметрами: amount=2500, pay_types=['c2c'], personal_id=8, wallet=None
2025-08-07 00:16:13,822 [INFO] api.api_manager - Попытка создания заказа через PSPWare (тип платежа: card -> c2c)
2025-08-07 00:16:13,823 [INFO] api.pspware_api - [PSPWareAPI] POST https://api.pspware.space/merchant/v2/orders Headers: {'X-API-KEY': 'd6e4d661-665d-4220-a635-4d072e56735b', 'Content-Type': 'application/json'} Payload: {'sum': 2500, 'currency': 'RUB', 'order_type': 'PAY-IN', 'pay_types': ['c2c'], 'geos': ['RU'], 'merchant_id': '03d6d735-a2b7-4b75-b5fa-43be40331bf8', 'order_id': '8', 'description': 'Exchange order 8'}
2025-08-07 00:16:14,243 [INFO] api.pspware_api - [PSPWareAPI] Response status 404 Body: {"detail":"Не удалось найти подходящие реквизиты ни по одному из способов оплаты."}
2025-08-07 00:16:14,244 [ERROR] api.pspware_api - [PSPWareAPI] Ошибка создания заказа: {'detail': 'Не удалось найти подходящие реквизиты ни по одному из способов оплаты.'}
2025-08-07 00:16:14,245 [WARNING] api.api_manager - PSPWare не смог создать заказ: Не удалось найти подходящие реквизиты ни по одному из способов оплаты.
2025-08-07 00:16:14,245 [INFO] api.api_manager - Вызов create_order для Greengo с параметрами: amount=2500, pay_types=card, personal_id=8, wallet=bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz
2025-08-07 00:16:14,246 [INFO] api.api_manager - Попытка создания заказа через Greengo (тип платежа: card -> card)
2025-08-07 00:16:14,246 [INFO] api.greengo_api - Создание Greengo ордера: {'payment_method': 'card', 'wallet': 'bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz', 'from_amount': '2500'}
2025-08-07 00:16:16,503 [ERROR] api.greengo_api - Greengo HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:16:16,505 [WARNING] api.api_manager - Greengo не смог создать заказ: HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:16:16,506 [INFO] api.api_manager - Вызов create_order для NicePay с параметрами: amount=2500, pay_types=sberbank_account_rub, personal_id=8, wallet=None
2025-08-07 00:16:16,506 [INFO] api.api_manager - Попытка создания заказа через NicePay (тип платежа: card -> sberbank_account_rub)
2025-08-07 00:16:16,507 [ERROR] api.api_manager - Недопустимый метод оплаты для NicePay: sberbank_account_rub
2025-08-07 00:16:16,508 [WARNING] handlers.user - NicePay order creation failed on attempt 1 for order 8: Invalid payment method: sberbank_account_rub
2025-08-07 00:16:45,528 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:16:45,528 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:16:45,797 [ERROR] asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py:64> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 66, in main
    await run_polling()
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 55, in run_polling
    await dp.start_polling(bot, skip_updates=True)
  File "C:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 543, in start_polling
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 75, in main
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2025-08-07 00:16:49,302 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:16:49,382 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:17:06,629 [INFO] aiogram.event - Update id=182330617 is handled. Duration 313 ms by bot id=8153616825
2025-08-07 00:17:07,408 [INFO] aiogram.event - Update id=182330618 is handled. Duration 94 ms by bot id=8153616825
2025-08-07 00:17:08,611 [INFO] aiogram.event - Update id=182330619 is handled. Duration 389 ms by bot id=8153616825
2025-08-07 00:17:10,836 [INFO] aiogram.event - Update id=182330620 is handled. Duration 407 ms by bot id=8153616825
2025-08-07 00:18:02,571 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:18:02,571 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:18:02,825 [ERROR] asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py:64> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 66, in main
    await run_polling()
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 55, in run_polling
    await dp.start_polling(bot, skip_updates=True)
  File "C:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 543, in start_polling
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 75, in main
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2025-08-07 00:18:06,125 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:18:06,196 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:18:07,048 [INFO] aiogram.event - Update id=182330621 is handled. Duration 421 ms by bot id=8153616825
2025-08-07 00:18:08,162 [INFO] aiogram.event - Update id=182330622 is handled. Duration 344 ms by bot id=8153616825
2025-08-07 00:18:09,014 [INFO] aiogram.event - Update id=182330623 is handled. Duration 265 ms by bot id=8153616825
2025-08-07 00:18:23,745 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:18:23,746 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:18:24,008 [ERROR] asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py:64> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 66, in main
    await run_polling()
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 55, in run_polling
    await dp.start_polling(bot, skip_updates=True)
  File "C:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 543, in start_polling
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 75, in main
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2025-08-07 00:18:27,329 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:18:27,409 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:18:31,431 [INFO] aiogram.event - Update id=182330624 is handled. Duration 280 ms by bot id=8153616825
2025-08-07 00:18:32,399 [INFO] aiogram.event - Update id=182330625 is handled. Duration 359 ms by bot id=8153616825
2025-08-07 00:18:33,248 [INFO] aiogram.event - Update id=182330626 is handled. Duration 328 ms by bot id=8153616825
2025-08-07 00:18:40,258 [INFO] aiogram.event - Update id=182330627 is handled. Duration 203 ms by bot id=8153616825
2025-08-07 00:18:48,963 [INFO] aiogram.event - Update id=182330628 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:18:50,066 [INFO] aiogram.event - Update id=182330629 is handled. Duration 92 ms by bot id=8153616825
2025-08-07 00:18:50,070 [INFO] api.api_manager - Вызов create_order для OnlyPays с параметрами: amount=2500, pay_types=sbp, personal_id=9, wallet=None
2025-08-07 00:18:50,070 [INFO] api.api_manager - Попытка создания заказа через OnlyPays (тип платежа: sbp -> sbp)
2025-08-07 00:18:54,135 [INFO] api.onlypays_api - OnlyPays create_order response (sum 2500): {'success': False, 'error': 'No available requisites'}
2025-08-07 00:18:54,136 [WARNING] api.api_manager - OnlyPays не смог создать заказ: No available requisites
2025-08-07 00:18:54,136 [INFO] api.api_manager - Вызов create_order для PSPWare с параметрами: amount=2500, pay_types=['sbp'], personal_id=9, wallet=None
2025-08-07 00:18:54,136 [INFO] api.api_manager - Попытка создания заказа через PSPWare (тип платежа: sbp -> sbp)
2025-08-07 00:18:54,136 [INFO] api.pspware_api - [PSPWareAPI] POST https://api.pspware.space/merchant/v2/orders Headers: {'X-API-KEY': 'd6e4d661-665d-4220-a635-4d072e56735b', 'Content-Type': 'application/json'} Payload: {'sum': 2500, 'currency': 'RUB', 'order_type': 'PAY-IN', 'pay_types': ['sbp'], 'geos': ['RU'], 'merchant_id': '03d6d735-a2b7-4b75-b5fa-43be40331bf8', 'order_id': '9', 'description': 'Exchange order 9'}
2025-08-07 00:18:54,772 [INFO] api.pspware_api - [PSPWareAPI] Response status 404 Body: {"detail":"Не удалось найти подходящие реквизиты ни по одному из способов оплаты."}
2025-08-07 00:18:54,773 [ERROR] api.pspware_api - [PSPWareAPI] Ошибка создания заказа: {'detail': 'Не удалось найти подходящие реквизиты ни по одному из способов оплаты.'}
2025-08-07 00:18:54,774 [WARNING] api.api_manager - PSPWare не смог создать заказ: Не удалось найти подходящие реквизиты ни по одному из способов оплаты.
2025-08-07 00:18:54,775 [INFO] api.api_manager - Вызов create_order для Greengo с параметрами: amount=2500, pay_types=sbp, personal_id=9, wallet=bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz
2025-08-07 00:18:54,776 [INFO] api.api_manager - Попытка создания заказа через Greengo (тип платежа: sbp -> sbp)
2025-08-07 00:18:54,777 [INFO] api.greengo_api - Создание Greengo ордера: {'payment_method': 'sbp', 'wallet': 'bc1qyk7c3nu3sqpygh8xdl2vdxwmr3w0jufp23ymxz', 'from_amount': '2500'}
2025-08-07 00:18:57,087 [ERROR] api.greengo_api - Greengo HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:18:57,088 [WARNING] api.api_manager - Greengo не смог создать заказ: HTTP 400: {"result":false,"message":"\u041d\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0445 \u0441\u0447\u0435\u0442\u043e\u0432"}
2025-08-07 00:18:57,089 [INFO] api.api_manager - Вызов create_order для NicePay с параметрами: amount=2500, pay_types=sbp_rub, personal_id=9, wallet=None
2025-08-07 00:18:57,090 [INFO] api.api_manager - Попытка создания заказа через NicePay (тип платежа: sbp -> sbp_rub)
2025-08-07 00:18:57,385 [INFO] api.nicepay_api - NicePay response: {'status': 'success', 'data': {'payment_id': 'UCy689-3c6b3d-d5ec94-1b0ab1-faaXvF', 'amount': 250000, 'currency': 'RUB', 'link': 'https://processinglink.io/pay/UCy689-3c6b3d-d5ec94-1b0ab1-faaXvF', 'expired': 1754533123}}
2025-08-07 00:18:57,387 [INFO] api.api_manager - Успешное создание заказа через NicePay: {'id': '9', 'order_id': '9', 'payment_url': 'https://processinglink.io/pay/UCy689-3c6b3d-d5ec94-1b0ab1-faaXvF', 'amount': 2500}
2025-08-07 00:22:35,142 [INFO] aiogram.event - Update id=182330630 is handled. Duration 296 ms by bot id=8153616825
2025-08-07 00:22:42,517 [INFO] aiogram.event - Update id=182330631 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 00:26:29,216 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 00:26:29,217 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 00:26:29,481 [ERROR] asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py:64> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 66, in main
    await run_polling()
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 55, in run_polling
    await dp.start_polling(bot, skip_updates=True)
  File "C:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 543, in start_polling
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 75, in main
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2025-08-07 00:26:32,945 [INFO] aiogram.dispatcher - Start polling
2025-08-07 00:26:33,024 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 12:39:43,444 [ERROR] aiogram.dispatcher - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2025-08-07 12:39:47,606 [WARNING] aiogram.dispatcher - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8153616825)
2025-08-07 12:39:48,704 [ERROR] aiogram.dispatcher - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-08-07 12:39:48,706 [WARNING] aiogram.dispatcher - Sleep for 1.345600 seconds and try again... (tryings = 1, bot id = 8153616825)
2025-08-07 12:39:50,055 [ERROR] aiogram.dispatcher - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-08-07 12:39:50,055 [WARNING] aiogram.dispatcher - Sleep for 1.851222 seconds and try again... (tryings = 2, bot id = 8153616825)
2025-08-07 12:39:51,908 [ERROR] aiogram.dispatcher - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2025-08-07 12:39:51,908 [WARNING] aiogram.dispatcher - Sleep for 2.489109 seconds and try again... (tryings = 3, bot id = 8153616825)
2025-08-07 12:39:54,658 [INFO] aiogram.dispatcher - Connection established (tryings = 4, bot id = 8153616825)
2025-08-07 12:39:54,973 [INFO] aiogram.event - Update id=182330633 is handled. Duration 313 ms by bot id=8153616825
2025-08-07 12:39:54,976 [INFO] aiogram.event - Update id=182330632 is handled. Duration 328 ms by bot id=8153616825
2025-08-07 12:39:54,978 [INFO] aiogram.event - Update id=182330634 is handled. Duration 311 ms by bot id=8153616825
2025-08-07 12:39:56,811 [INFO] aiogram.dispatcher - Polling stopped for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 12:39:56,818 [INFO] aiogram.dispatcher - Polling stopped
2025-08-07 12:39:57,089 [ERROR] asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py:64> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 788, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 66, in main
    await run_polling()
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 55, in run_polling
    await dp.start_polling(bot, skip_updates=True)
  File "C:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 543, in start_polling
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\behin\Documents\Oswaldo\Oswbit-Exchanger-tg\main.py", line 75, in main
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Users\behin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2025-08-07 12:40:01,526 [INFO] aiogram.dispatcher - Start polling
2025-08-07 12:40:01,610 [INFO] aiogram.dispatcher - Run polling for bot @OswaldoExchanger_bot id=8153616825 - 'Oswbit Exchanger'
2025-08-07 12:40:14,965 [INFO] aiogram.event - Update id=182330635 is handled. Duration 391 ms by bot id=8153616825
2025-08-07 12:40:26,426 [INFO] aiogram.event - Update id=182330636 is handled. Duration 360 ms by bot id=8153616825
2025-08-07 12:40:28,454 [INFO] aiogram.event - Update id=182330637 is handled. Duration 233 ms by bot id=8153616825
2025-08-07 12:40:29,924 [INFO] aiogram.event - Update id=182330638 is handled. Duration 233 ms by bot id=8153616825
2025-08-07 12:40:33,111 [INFO] aiogram.event - Update id=182330639 is handled. Duration 656 ms by bot id=8153616825
2025-08-07 12:40:35,123 [INFO] aiogram.event - Update id=182330640 is handled. Duration 140 ms by bot id=8153616825
2025-08-07 12:40:36,154 [INFO] aiogram.event - Update id=182330641 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 12:40:44,950 [INFO] aiogram.event - Update id=182330642 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 12:40:46,412 [INFO] aiogram.event - Update id=182330643 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 12:40:48,449 [INFO] aiogram.event - Update id=182330644 is handled. Duration 125 ms by bot id=8153616825
2025-08-07 12:40:49,362 [INFO] aiogram.event - Update id=182330645 is handled. Duration 109 ms by bot id=8153616825
2025-08-07 12:40:55,585 [INFO] aiogram.event - Update id=182330646 is handled. Duration 594 ms by bot id=8153616825
